### ISSUE TITLE
Use ADA_TOKEN environment variable to set the token file

### ISSUE THREAD

**Issue by LourensVeen** [sara-nl/SpiderScripts#11]
It would be nice if you could use an environment variable to set the token file, rather than having to pass it on the command line every time. Although it was pointed out to me that you can also set an alias
```
alias ada-mytoken ada --tokenfile /path/to/mytoken
```
which has the advantage that you can mix using multiple tokens by setting different aliases, if you want.

**Comment by onnozweers** [comment]
Thanks, nice idea! We'll do that.

**Comment by onnozweers** [comment]
It is already possible to define the tokenfile var in the /etc/ada.conf or ~/.ada/ada.conf file. You would probably also need to set `auth_method=token`. But I like the idea to also support environment vars.

**Comment by onnozweers** [comment]
Done: https://github.com/sara-nl/SpiderScripts/commit/09144639885977663d1eef4aa483fe2cecec972d

```
[surfadvisors-ozweers@wn-ui-01 ada]$ export ada_tokenfile=~/ada4nlesc/course_package/nlesc_token.conf

[surfadvisors-ozweers@wn-ui-01 ada]$ export ada_api=https://dcacheview.grid.surfsara.nl:22880/api/v1

[surfadvisors-ozweers@wn-ui-01 ada]$ ./ada --list /lourens
test_file.jpg
```
You'll need to export the vars to make it work.

**Comment by LourensVeen** [comment]
Yep, that works great. Thanks @onnozweers!
